# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

variables:
- group: vnet_variables

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sh ./ipcalc.sh $(vnetAdrRange) $(subnetSize)
